# This is a basic workflow that is manually triggered

name: post to gitea

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  post:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - name: regex dashes
      run:  echo "GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY | sed 's/ /-/g')" >> $GITHUB_ENV
    - name: regex username
      run:  echo "GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY | sed 's?jamcdon/??g')" >> $GITHUB_ENV
    - name: redirect secret to file
      run: echo $API_KEY | sed -e 's/\(.\)/\1 /g'
      env:
        $API_KEY: ${{ secrets.API_KEY }}
    - name: chmod +x
      run: chmod +x ci-cd/post-reqwest-1.1
    - name: run binary
      env:
        $API_KEY: ${{ secrets.API_KEY }}
      run: ./ci-cd/post-reqwest-1.1 $KEY $GITHUB_REPOSITORY
