# This is a basic workflow that is manually triggered

name: post to gitea

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  post:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: regex fn
      run: proj=$(echo $GITHUB_REPOSITORY | sed 's/ /-/g')
    - name: change dir
      run: cd ci-cd/
    - name: chmod +x
      run: chmod +x post-reqwest-1.1
    - name: run binary
      run: ./post-reqwest-1.1 $API_KEY $proj
